export const el = {
  arena: document.getElementById("arena")!,
  battleStage: document.getElementById("battle-stage")!,
  playerPanel: document.getElementById("player-panel")!,
  playerStatus: document.querySelector("#player-panel .hero-status") as HTMLElement,
  foePanel: document.getElementById("foe-panel")!,
  foeStatus: document.querySelector("#foe-panel .enemy-status") as HTMLElement,
  damageLayer: document.getElementById("damage-layer")!,
  heroLevelUpLayer: document.getElementById("hero-level-up-layer")!,
  xpBar: document.getElementById("xp-bar")!,
  xpFill: document.getElementById("xp-fill")!,
  xpText: document.getElementById("xp-text")!,
  bestWave: document.getElementById("stat-best-wave")!,
  runs: document.getElementById("stat-runs")!,
  waveBanner: document.getElementById("wave-banner")!,
  playerHpFill: document.getElementById("player-hp-fill")!,
  playerHpText: document.getElementById("player-hp-text")!,
  playerLevel: document.getElementById("player-level")!,
  playerAttack: document.getElementById("player-attack")!,
  playerBuff: document.getElementById("player-buff")!,
  playerHypeWrap: document.getElementById("player-hype-wrap")!,
  playerHypeBar: document.getElementById("player-hype-bar")!,
  playerHypeFill: document.getElementById("player-hype-fill")!,
  playerEmoji: document.getElementById("hero-emoji")!,
  playerName: document.getElementById("hero-name")!,
  foeName: document.getElementById("foe-name")!,
  foeLevel: document.getElementById("foe-level")!,
  foeAttack: document.getElementById("foe-attack")!,
  foeBuff: document.getElementById("foe-buff")!,
  foeHypeWrap: document.getElementById("foe-hype-wrap")!,
  foeHypeBar: document.getElementById("foe-hype-bar")!,
  foeHypeFill: document.getElementById("foe-hype-fill")!,
  foeEmoji: document.getElementById("foe-emoji")!,
  foeHpFill: document.getElementById("foe-hp-fill")!,
  foeHpText: document.getElementById("foe-hp-text")!,
  turnLabel: document.getElementById("turn-label")!,
  battleText: document.getElementById("battle-text")!,
  actions: document.getElementById("actions")!,
  healBtn:
    document.getElementById("cmd-heal") ??
    document.querySelector<HTMLButtonElement>('[data-action="heal"]')!,
  danceBtn:
    document.getElementById("cmd-dance") ??
    document.querySelector<HTMLButtonElement>('[data-action="dance"]')!,
  attackBtn:
    document.getElementById("cmd-attack") ??
    document.querySelector<HTMLButtonElement>('[data-action="attack"]')!,
  healTeachPopup: document.getElementById("cmd-heal-teach")!,
  danceTeachPopup: document.getElementById("cmd-dance-teach")!,
  runTeachPopup: document.getElementById("cmd-run-teach")!,
  runBtn:
    document.getElementById("cmd-run") ??
    document.querySelector<HTMLButtonElement>('[data-action="run"]')!,
  recordsBar: document.querySelector(".records-bar") as HTMLElement,
  gameOver: document.getElementById("game-over")!,
  victoryEmojiLayer: document.getElementById("victory-emoji-layer")!,
  gameOverTag: document.getElementById("game-over-tag")!,
  gameOverSummary: document.getElementById("game-over-summary")!,
  gameOverBattleLog: document.getElementById("game-over-battle-log")!,
  gameOverLog: document.querySelector(".game-over-log") as HTMLDetailsElement,
  restartLabel: document.querySelector("#restart-btn .cmd-label")!,
  restartBtn: document.getElementById("restart-btn")!,
  quitBtn: document.getElementById("quit-btn")!,
  resetStatsBtn: document.getElementById("reset-stats-btn")!,
  footerMore: document.getElementById("footer-more") as HTMLDetailsElement,
  footerSound: document.getElementById("footer-sound") as HTMLDetailsElement,
  helpBtn: document.getElementById("help-btn")!,
  helpOverlay: document.getElementById("help-overlay")!,
  helpPanel: document.getElementById("help-panel")!,
  helpClose: document.getElementById("help-close")!,
  themeToggle: document.getElementById("theme-toggle")!,
  themeToggleIcon: document.querySelector("#theme-toggle .theme-toggle-icon")!,
  soundMenuToggle: document.querySelector("#footer-sound .sound-menu-toggle")!,
  soundMenuToggleIcon: document.querySelector("#footer-sound .sound-menu-toggle-icon")!,
  musicLevelBtn: document.getElementById("music-level-btn")!,
  sfxLevelBtn: document.getElementById("sfx-level-btn")!,
  confirmOverlay: document.getElementById("confirm-overlay")!,
  confirmPanel: document.getElementById("confirm-panel")!,
  confirmTitle: document.getElementById("confirm-title")!,
  confirmMessage: document.getElementById("confirm-message")!,
  confirmOk: document.getElementById("confirm-ok")!,
  confirmCancel: document.getElementById("confirm-cancel")!,
  setupOverlay: document.getElementById("character-setup")!,
  setupSubtitle: document.getElementById("setup-subtitle")!,
  heroPicker: document.getElementById("hero-picker")!,
  heroNameInput: document.getElementById("hero-name-input") as HTMLInputElement,
  heroColorSwatches: document.getElementById("hero-color-swatches")!,
  heroColorToggle: document.getElementById("hero-color-toggle") as HTMLButtonElement,
  heroColorPopup: document.getElementById("hero-color-popup")!,
  setupStartBtn: document.getElementById("setup-start-btn") as HTMLButtonElement,
  setupHint: document.getElementById("setup-hint")!,
  gameShell: document.querySelector(".game-shell") as HTMLElement,
};
