import { createCombatHintsState } from "../lib/combat-hints.js";
import type { ColorMode } from "../lib/color-mode.js";
import {
  DEFAULT_HERO_COLOR_THEME,
  DEFAULT_HERO_EMOJI,
  DEFAULT_HERO_LABEL,
  DEFAULT_HERO_NAME,
} from "./constants.js";
import type {
  BattleLogEntry,
  CombatTeachPopupId,
  Enemy,
  FoeColorTheme,
  FoeTemplate,
  GameSnapshot,
  HeroColorTheme,
  Player,
} from "./types.js";

export const gameState = {
  player: {
    name: DEFAULT_HERO_NAME,
    hp: 20,
    maxHp: 20,
    attack: 5,
    emoji: DEFAULT_HERO_EMOJI,
  } satisfies Player,
  foe: null as Enemy | null,
  foeOrder: [] as FoeTemplate[],
  foeQueue: [] as string[],
  deferredFoeIds: [] as string[],
  turn: 1,
  wave: 1,
  hypeLevel: 0,
  foeHypeLevel: 0,
  phase: "combat" as GameSnapshot["phase"],
  combatHints: createCombatHintsState(),
  pendingHeroEmoji: DEFAULT_HERO_EMOJI,
  pendingHeroLabel: DEFAULT_HERO_LABEL,
  heroColorTheme: DEFAULT_HERO_COLOR_THEME as HeroColorTheme,
  pendingHeroColorTheme: DEFAULT_HERO_COLOR_THEME as HeroColorTheme,
  foeColorTheme: "amber" as FoeColorTheme,
  lastFoeColorTheme: null as FoeColorTheme | null,
  defeatVerbIndex: 0,
  combatBusy: false,
  combatActionGeneration: 0,
  awaitingFoeResponse: false,
  suppressFoePanelRender: false,
  displayedPlayerHype: 0,
  displayedFoeHype: 0,
  skipPlayerHypeTeachThisRender: false,
  suppressTeachFlashesThisRender: false,
  temporarilyClosedTeachPopups: new Set<CombatTeachPopupId>(),
  setupHintForced: false,
  setupColorPickerBound: false,
  waveAttempt: 1,
  currentColorMode: "dark" as ColorMode,
  debugInstantTransitions: false,
  confirmResolve: null as ((confirmed: boolean) => void) | null,
  footerTeachPopupResizeBound: false,
  battleLogHistory: [] as BattleLogEntry[],
};
