import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

const htmlDir = join(dirname(fileURLToPath(import.meta.url)), "../../html/partials");
const root = join(dirname(fileURLToPath(import.meta.url)), "../..");

/** HTML partials assembled into index.html, mirroring src/game/* modules. */
export const HTML_PARTIAL_FILES = [
  "head.html",
  "base.html",
  "persistence.html",
  "app-help.html",
  "setup.html",
  "presentation.html",
  "combat.html",
  "game-over.html",
  "presentation-close.html",
  "combat-teach-dock.html",
  "app-footer.html",
] as const;

export function readHtmlPartial(name: (typeof HTML_PARTIAL_FILES)[number]): string {
  return readFileSync(join(htmlDir, name), "utf8");
}

export function readAssembledHtml(): string {
  return readFileSync(join(root, "index.html"), "utf8");
}

/** IDs referenced from src/game/dom.ts — partials must preserve them. */
export const REQUIRED_DOM_IDS = [
  "arena",
  "battle-stage",
  "player-panel",
  "foe-panel",
  "damage-layer",
  "hero-level-up-layer",
  "xp-bar",
  "xp-fill",
  "xp-text",
  "stat-best-wave",
  "stat-runs",
  "wave-banner",
  "player-hp-fill",
  "player-hp-text",
  "player-level",
  "player-attack",
  "player-buff",
  "player-hype-wrap",
  "player-hype-bar",
  "player-hype-fill",
  "hero-emoji",
  "hero-name",
  "foe-name",
  "foe-level",
  "foe-attack",
  "foe-buff",
  "foe-hype-wrap",
  "foe-hype-bar",
  "foe-hype-fill",
  "foe-emoji",
  "foe-hp-fill",
  "foe-hp-text",
  "turn-label",
  "battle-text",
  "actions",
  "cmd-heal",
  "cmd-dance",
  "cmd-attack",
  "cmd-heal-teach",
  "cmd-dance-teach",
  "cmd-run-teach",
  "cmd-run",
  "game-over",
  "victory-emoji-layer",
  "game-over-tag",
  "game-over-summary",
  "game-over-battle-log",
  "restart-btn",
  "quit-btn",
  "reset-stats-btn",
  "footer-more",
  "help-btn",
  "help-overlay",
  "help-panel",
  "help-close",
  "theme-toggle",
  "footer-sound",
  "music-level-btn",
  "sfx-level-btn",
  "confirm-overlay",
  "confirm-panel",
  "confirm-title",
  "confirm-message",
  "confirm-ok",
  "confirm-cancel",
  "character-setup",
  "setup-subtitle",
  "hero-picker",
  "hero-name-input",
  "hero-color-swatches",
  "hero-color-toggle",
  "hero-color-popup",
  "setup-start-btn",
  "setup-hint",
  "teach-popup-dock",
] as const;

export const DOM_IDS_BY_PARTIAL: Record<(typeof HTML_PARTIAL_FILES)[number], readonly string[]> = {
  "head.html": [],
  "base.html": [],
  "persistence.html": [
    "confirm-overlay",
    "confirm-panel",
    "confirm-title",
    "confirm-message",
    "confirm-ok",
    "confirm-cancel",
  ],
  "app-help.html": ["help-overlay", "help-panel", "help-close"],
  "setup.html": [
    "character-setup",
    "setup-subtitle",
    "hero-picker",
    "hero-name-input",
    "hero-color-toggle",
    "hero-color-popup",
    "hero-color-swatches",
    "setup-start-btn",
    "setup-hint",
  ],
  "presentation.html": [
    "wave-banner",
    "turn-label",
    "xp-bar",
    "xp-fill",
    "xp-text",
    "arena",
    "battle-stage",
    "player-panel",
    "hero-name",
    "player-hp-fill",
    "player-hp-text",
    "player-level",
    "player-attack",
    "player-buff",
    "player-hype-wrap",
    "player-hype-bar",
    "player-hype-fill",
    "hero-level-up-layer",
    "hero-emoji",
    "foe-panel",
    "foe-name",
    "foe-hp-fill",
    "foe-hp-text",
    "foe-level",
    "foe-attack",
    "foe-buff",
    "foe-hype-wrap",
    "foe-hype-bar",
    "foe-hype-fill",
    "foe-emoji",
    "damage-layer",
  ],
  "combat.html": ["battle-text", "actions", "cmd-attack", "cmd-heal", "cmd-heal-teach", "cmd-dance", "cmd-run"],
  "game-over.html": [
    "game-over",
    "victory-emoji-layer",
    "game-over-tag",
    "game-over-summary",
    "game-over-battle-log",
    "restart-btn",
  ],
  "presentation-close.html": [],
  "combat-teach-dock.html": ["teach-popup-dock", "cmd-dance-teach", "cmd-run-teach"],
  "app-footer.html": [
    "stat-best-wave",
    "stat-runs",
    "help-btn",
  "theme-toggle",
  "footer-sound",
  "music-level-btn",
  "sfx-level-btn",
  "footer-more",
    "quit-btn",
    "reset-stats-btn",
  ],
};
